version: '3'
services:
  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_URL: redis://redis:6379
    depends_on:
      - redis
    ports:
      - "8080:3000"  

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
